name: "osnet"
platform: "tensorrt_plan"
max_batch_size: 64

input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 128 ]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 4000
  preferred_batch_size: [ 8, 16, 32, 64 ]
}

instance_group [
  {
    kind: KIND_GPU
    gpus: [ 0 ]
    count: 1
  }
]
