%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0.3

TargetManagement:
  minTrackerConfidence: 0.4
  maxShadowTrackingAge: 60
  probationAge: 3
  earlyTerminationAge: 2
  enableBboxUnClipping: 0
  maxTargetsPerStream: 50

TrajectoryManagement:
  useUniqueID: 0

DataAssociator:
  dataAssociatorType: 1
  associationMatcherType: 1
  checkClassMatch: 1
  minMatchingScore4Overall: 0.0

StateEstimator:
  stateEstimatorType: 2
